##########################################################
###################  生产环境的profile  ###################
##########################################################
spring:
  profiles: produce
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.13.55.232:3306/guns?useSSL=false&characterEncoding=utf8
    username: root
    password: 1qaz!QAZ
    db-name: guns
    filters: log4j,wall,mergeStat

#flowable数据源和多数据源配置
guns:
  flowable:
    datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.13.55.232:3306/guns?useSSL=false&characterEncoding=utf8
    username: root
    password: 1qaz!QAZ
  muti-datasource:
    open: true
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.13.55.232:3306/guns?useSSL=false&characterEncoding=utf8
    username: root
    password: 1qaz!QAZ