
###################  项目启动端口  ###################
server:
  port: 8080


###################  guns配置  ###################
guns:
  swagger-open: true #是否开启swagger (true/false)
  kaptcha-open: false #是否开启登录时验证码 (true/false)
  #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  spring-session-open: true #是否开启spring session,如果是多机环境需要开启(true/false)
#  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
#  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒


###################  spring配置  ###################
spring:
  profiles:
    active: @spring.active@
  mvc:
    view:
      prefix: /pages
  redis:
    host: 106.13.55.232
    port: 6379
    password: 12qw!@QW
  rabbitmq:
    host: 106.13.55.232
    port: 5672
    username: admin
    password: admin
    virtual-host: /
  devtools:
    restart:
      enabled: false #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: assets/**,pages/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

#关闭定时任务JOB
flowable:
  async-executor-activate: false

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/stylefeng/guns/**/mapping/*.xml
  typeAliasesPackage: com.stylefeng.guns.modular.**.model

logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: guns.log

---



